const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const id='11111111-1111-4111-8111-111111111111';
function edge({gate={ok:true},trusted=true,turnstile=true,verdict=true}={}){let handler;const calls=[];const env={SUPABASE_URL:'https://project.invalid',SUPABASE_SECRET_KEYS:JSON.stringify({default:'sb_secret_test'}),TERRA_ALLOWED_ORIGINS:'https://site.invalid',TURNSTILE_SECRET_KEY:turnstile?'secret':null};const context={Response,URL,URLSearchParams,TextEncoder,Uint8Array,AbortSignal,crypto:webcrypto,Deno:{env:{get:k=>env[k]},serve:f=>handler=f},fetch:async(url,opts)=>{const name=url.split('/').pop();calls.push(name);if(name==='terra_contact_proxy_valid')return Response.json(trusted);if(name==='terra_contact_gate')return Response.json(gate);if(name==='siteverify')return Response.json({success:verdict,action:'terra_contact',hostname:'site.invalid'});if(name==='terra_contact_deliver'){assert.equal(JSON.parse(opts.body).p_user,null);return Response.json({phone:'5532999999999',listing_id:id});}throw Error(name);}};vm.createContext(context);vm.runInContext(fs.readFileSync('supabase/functions/terra-contact/index.ts','utf8'),context);return {calls,call:(token,proxy='a'.repeat(64))=>handler(new Request('https://project.invalid/contact',{method:'POST',headers:{'x-terra-proxy':proxy},body:JSON.stringify({session:id,listing:id,ip:'b'.repeat(64),origin:'https://site.invalid',token,user_id:'forged'})}))};}
test('anonymous contact works through trusted proxy and ignores forged account attribution',async()=>{const s=edge(),r=await s.call();assert.equal(r.status,200);assert.equal((await r.json()).url,'https://wa.me/5532999999999');assert.ok(s.calls.indexOf('terra_contact_gate')<s.calls.indexOf('terra_contact_deliver'));});
test('untrusted proxy cannot inspect contacts',async()=>{const s=edge({trusted:false});assert.equal((await s.call()).status,403);assert.equal(s.calls.includes('terra_contact_deliver'),false);});
test('hard limits cannot be overridden by captcha',async()=>{const s=edge({gate:{error:'RATE_LIMIT'}});assert.equal((await s.call('token')).status,429);assert.equal(s.calls.includes('terra_contact_deliver'),false);});
test('suspicious contact requires successful server Turnstile verification',async()=>{for(const opts of [{},{verdict:false},{turnstile:false}]){const s=edge({gate:{error:'CAPTCHA_REQUIRED'},...opts});const r=await s.call(opts.verdict===false||opts.turnstile===false?'token':undefined);assert.notEqual(r.status,200);assert.equal(s.calls.includes('terra_contact_deliver'),false);}const s=edge({gate:{error:'CAPTCHA_REQUIRED'}});assert.equal((await s.call('token')).status,200);});
test('website contact proxy ignores forged identity and sends only server-derived visitor hash',async()=>{const previous=global.fetch;const {createWorker}=await import('../server/site-worker.mjs');const worker=createWorker({},{});try{global.fetch=async(url,options)=>{const b=JSON.parse(options.body);assert.match(b.ip,/^[a-f0-9]{64}$/);assert.notEqual(b.ip,'forged');assert.equal(b.user_id,undefined);assert.equal(b.origin,'https://site.invalid');assert.equal(options.headers['x-terra-proxy'],'server-secret');return Response.json({url:'https://wa.me/5532999999999'});};const req=new Request('https://site.invalid/api/contact',{method:'POST',headers:{Origin:'https://site.invalid','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify({session:id,listing:id,ip:'forged',user_id:id})});Object.defineProperty(req,'cf',{value:{}});const response=await worker.fetch(req,{TERRA_CONTACT_PROXY_KEY:'server-secret'});assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');}finally{global.fetch=previous;}});
test('website rejects foreign origins and unavailable trusted network context',async()=>{const {createWorker}=await import('../server/site-worker.mjs');const w=createWorker({},{});const foreign=await w.fetch(new Request('https://site.invalid/api/contact',{method:'POST',headers:{Origin:'https://evil.invalid'}}));assert.equal(foreign.status,403);const missing=await w.fetch(new Request('https://site.invalid/api/contact',{method:'POST',headers:{Origin:'https://site.invalid','CF-Connecting-IP':'spoof'}}),{TERRA_CONTACT_PROXY_KEY:'secret'});assert.equal(missing.status,503);});
