const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs');
const feature={geometry:{coordinates:[-43.3501129,-21.7609533]},properties:{name:'Juiz de Fora',state:'Minas Gerais',countrycode:'BR',type:'city',osm_value:'municipality',extent:[-43.685934,-21.520535,-43.146653,-21.999342]}};
function setup(responses){const calls=[];const ctx={URL,URLSearchParams,AbortSignal,setTimeout,window:{},fetch:async url=>{calls.push(String(url));const body=responses.shift();return {ok:true,json:async()=>body}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/location.js','utf8'),ctx);return {api:ctx.window.TerraLocation,calls};}
test('municipality result preserves Photon extent axis order and resolves Brazilian state',()=>{const s=setup([]),p=s.api.resultFromFeature(feature);assert.equal(p.city,'Juiz de Fora');assert.equal(p.state,'MG');assert.equal(p.cityLevel,true);assert.equal(p.bounds.south,-21.999342);assert.equal(p.bounds.west,-43.685934);});
test('invalid CEP does not contact any provider',async()=>{const s=setup([]);await assert.rejects(s.api.search('12345'),/8 dígitos/);assert.equal(s.calls.length,0);});
test('missing CEP reports a useful error',async()=>{const s=setup([{erro:true}]);await assert.rejects(s.api.search('99999-999'),/CEP não encontrado/);assert.equal(s.calls.length,1);});
test('CEP is resolved to an address before geocoding',async()=>{const road={geometry:{coordinates:[-43.35,-21.76]},properties:{name:'Rua Halfeld',city:'Juiz de Fora',state:'Minas Gerais',countrycode:'BR',type:'street'}};const s=setup([{cep:'36010-000',logradouro:'Rua Halfeld',bairro:'Centro',localidade:'Juiz de Fora',uf:'MG'},{features:[road]}]);const result=await s.api.search('36010-000');assert.match(s.calls[0],/36010000/);assert.ok(new URL(s.calls[1]).searchParams.get('q').includes('Rua Halfeld'));assert.equal(result[0].cityLevel,false);assert.equal(result[0].city,'Juiz de Fora');});
test('repeated searches use cached results and exclude foreign results',async()=>{const foreign={...feature,properties:{...feature.properties,countrycode:'PT'}};const s=setup([{features:[feature,foreign]}]);assert.equal((await s.api.search('Juiz de Fora')).length,1);await s.api.search('juiz de fora');assert.equal(s.calls.length,1);});
