const {test}=require('node:test'),assert=require('node:assert/strict');
const id='11111111-1111-4111-8111-111111111111';
async function setup(){const {createWorker}=await import('../server/site-worker.mjs');const html='<html><head><!-- TERRA_METADATA --></head><body>Terra</body></html>';return createWorker({'/index.html':{type:'text/html',data:Buffer.from(html).toString('base64')}},{version:'1.0.6',commit:'fixture'});}
test('home has a canonical institutional social preview using the trusted origin',async()=>{const w=await setup(),r=await w.fetch(new Request('https://attacker.invalid/')),html=await r.text();assert.match(html,/og:image/);assert.match(html,/terraavistaimoveis.com.br\/og.png/);assert.doesNotMatch(html,/attacker/);assert.equal(r.headers.get('Cache-Control'),'public, max-age=0, must-revalidate');});
test('private, paused, unknown and failed public lookups receive no preview and noindex',async()=>{const previous=global.fetch;try{for(const outcome of ['draft','paused','missing','failure']){global.fetch=async()=>{if(outcome==='failure')throw Error('offline');return Response.json([]);};const w=await setup(),r=await w.fetch(new Request('https://terra.invalid/?terreno='+id)),html=await r.text();assert.match(html,/noindex/);assert.doesNotMatch(html,/og:image|og:title|twitter:card/);}}finally{global.fetch=previous;}});
test('public listing metadata uses anonymous filtering and never forwards a visitor token',async()=>{const previous=global.fetch;try{global.fetch=async(url,options)=>{assert.equal(url.searchParams.get('status'),'in.(published,reserved,sold)');assert.equal(options.headers.Authorization,undefined);return Response.json([{id}]);};const w=await setup(),r=await w.fetch(new Request('https://terra.invalid/?terreno='+id,{headers:{Authorization:'Bearer private'}}));assert.match(await r.text(),new RegExp('og:url.*terreno='+id));}finally{global.fetch=previous;}});
test('recovery links never get indexed or copied into metadata and version is identifiable',async()=>{const w=await setup(),r=await w.fetch(new Request('https://terra.invalid/?recovery=1&code=private'));assert.doesNotMatch(await r.text(),/code=private|og:image/);const v=await w.fetch(new Request('https://terra.invalid/version.json'));assert.deepEqual(await v.json(),{version:'1.0.6',commit:'fixture'});const sitemap=await(await w.fetch(new Request('https://terra.invalid/sitemap.xml'))).text();assert.doesNotMatch(sitemap,/terreno=|draft|paused/);});
test('public listing links get a preview with their own title, price, area, place and cover photo',async()=>{const previous=global.fetch;try{global.fetch=async url=>{assert.match(url.searchParams.get('select'),/terra_listing_photos/);return Response.json([{id,title:'Casa com 3 quartos',price_brl:850000,area_m2:364,city:'Juiz de Fora',state:'MG',neighborhood:'Cascatinha',category:'casa',details:{built_area_m2:185,bedrooms:3},revision:4,terra_listing_photos:[{storage_path:'x.jpg'}]}]);};
 const w=await setup(),html=await(await w.fetch(new Request('https://terra.invalid/?terreno='+id))).text();
 assert.match(html,/og:title" content="Casa com 3 quartos"/);assert.match(html,/og:description" content="R\$ 850\.000 · 185 m² · 3 quartos · Cascatinha, Juiz de Fora - MG"/);assert.ok(html.includes('og:image" content="https://terraavistaimoveis.com.br/og/listing/'+id+'.jpg?r=4"'));
}finally{global.fetch=previous;}});
test('short links resolve only public listings and the cover route falls back to the institutional image',async()=>{const previous=global.fetch;try{
 global.fetch=async url=>{assert.equal(url.searchParams.get('short_code'),'eq.kb9gg2');assert.equal(url.searchParams.get('status'),'in.(published,reserved,sold)');return Response.json([{id}]);};
 const w=await setup();let r=await w.fetch(new Request('https://terra.invalid/i/kb9gg2'));assert.equal(r.status,302);assert.match(r.headers.get('Location'),new RegExp('/\?terreno='+id+'$'));
 r=await w.fetch(new Request('https://terra.invalid/i/NOT-A-CODE'));assert.equal(r.status,404);
 global.fetch=async()=>Response.json([]);r=await w.fetch(new Request('https://terra.invalid/og/listing/'+id+'.jpg'));assert.equal(r.status,302);assert.match(r.headers.get('Location'),/\/og\.png/);
}finally{global.fetch=previous;}});
