begin;
select set_config('qa.a',gen_random_uuid()::text,true),set_config('qa.b',gen_random_uuid()::text,true),set_config('qa.listing',gen_random_uuid()::text,true),set_config('qa.session',gen_random_uuid()::text,true),set_config('qa.ip',md5(gen_random_uuid()::text)||md5(gen_random_uuid()::text),true);
insert into auth.users(id,aud,role,email,raw_user_meta_data,created_at,updated_at) select current_setting('qa.'||w)::uuid,'authenticated','authenticated',current_setting('qa.'||w)||'@example.invalid','{"display_name":"QA imobiliária"}',now(),now() from unnest(array['a','b'])t(w);
insert into auth.sessions(id,user_id,created_at,updated_at) select current_setting('qa.'||w)::uuid,current_setting('qa.'||w)::uuid,now(),now() from unnest(array['a','b'])t(w);
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('qa.a'),'role','authenticated','session_id',current_setting('qa.a'))::text,true);
set local role authenticated;
insert into public.terra_listings(id,title,city,state,category,price_brl,status,boundary_geojson) values(current_setting('qa.listing')::uuid,'QA contato','Juiz de Fora','MG','residencial',100000,'published','{"type":"Polygon","coordinates":[[[-43,-21],[-42.999,-21],[-42.999,-20.999],[-43,-21]]]}');
insert into public.terra_contact_settings(phone,enabled) values('5532999999999',true);
update public.terra_profiles set account_type='imobiliaria',creci='12345-J',description='QA',website='https://example.invalid',instagram='qa.imobiliaria' where id=auth.uid();
reset role;
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
do $$begin
 if (public.terra_advertiser(current_setting('qa.a')::uuid)->>'creci')<>'12345-J' then raise exception 'FAIL public CRECI';end if;
 if public.terra_advertiser(current_setting('qa.a')::uuid)?'phone' then raise exception 'FAIL phone exposure';end if;
 begin perform public.terra_professional_dashboard();raise exception 'FAIL anonymous dashboard';exception when insufficient_privilege then null;end;
 begin perform public.terra_contact_deliver(current_setting('qa.listing')::uuid,null,current_setting('qa.session')::uuid);raise exception 'FAIL direct contact bypass';exception when insufficient_privilege then null;end;
 begin perform public.terra_contact_gate(current_setting('qa.ip'),gen_random_uuid(),true);raise exception 'FAIL forged captcha';exception when insufficient_privilege then null;end;
end $$;
reset role;
do $$declare r jsonb;begin
 r:=public.terra_contact_deliver(current_setting('qa.listing')::uuid,null,current_setting('qa.session')::uuid);if r->>'phone'<>'5532999999999' then raise exception 'FAIL anonymous contact';end if;
 perform public.terra_contact_deliver(current_setting('qa.listing')::uuid,null,current_setting('qa.session')::uuid);
 if (select count(*) from public.terra_leads where listing_id=current_setting('qa.listing')::uuid)<>1 then raise exception 'FAIL lead deduplication';end if;
 for i in 1..6 loop r:=public.terra_contact_gate(current_setting('qa.ip'),gen_random_uuid(),false);end loop;
 if r->>'error'<>'CAPTCHA_REQUIRED' then raise exception 'FAIL rotating session bypass';end if;
 update private_terra.contact_limits set hits=60 where key='ip:'||current_setting('qa.ip');r:=public.terra_contact_gate(current_setting('qa.ip'),gen_random_uuid(),true);if r->>'error'<>'RATE_LIMIT' then raise exception 'FAIL hard limit bypass';end if;
end $$;
insert into public.terra_views(listing_id,session_id,window_start,created_at) values(current_setting('qa.listing')::uuid,gen_random_uuid(),now(),now()),(current_setting('qa.listing')::uuid,gen_random_uuid(),now()-interval '40 days',now()-interval '40 days');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('qa.a'),'role','authenticated','session_id',current_setting('qa.a'))::text,true);
set local role authenticated;
do $$declare r jsonb;begin r:=public.terra_professional_dashboard();if (r->>'active')::int<>1 or (r->>'views')::int<>1 or (r->>'contacts')::int<>1 then raise exception 'FAIL 30-day owner metrics: %',r;end if;end $$;
update public.terra_listings set status='paused' where id=current_setting('qa.listing')::uuid;
reset role;
do $$begin begin perform public.terra_contact_deliver(current_setting('qa.listing')::uuid,null,gen_random_uuid());raise exception 'FAIL private contact allowed';exception when others then if sqlerrm='FAIL private contact allowed' then raise;end if;end;end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('qa.b'),'role','authenticated','session_id',current_setting('qa.b'))::text,true);
set local role authenticated;
do $$declare r jsonb;begin r:=public.terra_professional_dashboard();if (r->>'contacts')::int<>0 or jsonb_array_length(r->'top')<>0 then raise exception 'FAIL other account metrics';end if;
 update public.terra_profiles set creci='forged' where id=current_setting('qa.a')::uuid;if found then raise exception 'FAIL editing another agency';end if;
end $$;
reset role;
rollback;
